const express = require('express')
const passport = require('../config/passport')
const router = express.Router()
const { apiErrorHandler } = require('../middleware/error-handler')
const { authenticated } = require('../middleware/auth')
const userController = require('../controllers/user-controller')
const storyController = require('../controllers/story-controller')
const upload = require('../middleware/multer')

router.post('/stories/p/:storyId')
router.get('/:userName/followers', userController.getFollowers)
router.get('/:userName/followings', userController.getFollowings)
router.get('/me/stories/drafts', authenticated, userController.getDraftStory)
router.get('/me/stories/public', authenticated, userController.getPublishedStory)
router.get('/me/stories/responses', authenticated, userController.getResponses)
router.put('/:userName', authenticated, upload.single('avatar'), userController.putUser)
router.get('/:userName', userController.getUser)
router.post('/upload-file', upload.single('profile_img'), storyController.uploadImg)
router.post('/signIn', passport.authenticate('local'), userController.signIn)

router.use('/', apiErrorHandler)
module.exports = router
