const express = require('express')
const passport = require('../config/passport')
const router = express.Router()
const { apiErrorHandler } = require('../middleware/error-handler')
const { authenticated } = require('../middleware/auth')
const userController = require('../controllers/user-controller')
const storyController = require('../controllers/story-controller')
const upload = require('../middleware/multer')

router.get('/users/:userName/followers', userController.getFollowers)
router.get('/users/:userName/followings', userController.getFollowings)
router.get('/users/draft', authenticated, userController.getDraftStory)
router.get('/users/published', authenticated, userController.getPublishedStory)
router.get('/users/responses', authenticated, userController.getResponses)
router.get('/users/:userName', userController.getUser)
router.put('/users/:userName', authenticated, upload.single('avatar'), userController.putUser)
router.post('/upload-file', upload.single('profile_img'), storyController.uploadImg)
router.post('/signIn', passport.authenticate('local'), userController.signIn)

router.use('/', apiErrorHandler)
module.exports = router
