const express = require('express')
const passport = require('../config/passport')
const router = express.Router()
const { apiErrorHandler } = require('../middleware/error-handler')
const { authenticated, localAuthenticate } = require('../middleware/auth')
const userController = require('../controllers/user-controller')
const storyController = require('../controllers/story-controller')
const clapController = require('../controllers/clap-controller')
const upload = require('../middleware/multer')
const followshipController = require('../controllers/followship-controller')

router.put('/p/storyCode/edit', storyController.putStory)
router.post('/userName/storyId', storyController.getStory)
router.delete('/following', authenticated, followshipController.removeFollowing)
router.post('/following', authenticated, followshipController.addFollowing)
router.post('/clap', authenticated, clapController.addClap)
router.delete('/clap', authenticated, clapController.removeClap)
router.post('/stories/p/storyId')
router.post('/userName/followers', userController.getFollowers)
router.post('/userName/followings', userController.getFollowings)
router.get('/me/stories/drafts', authenticated, userController.getDraftStory)
router.get('/me/stories/public', authenticated, userController.getPublishedStory)
router.get('/me/stories/responses', authenticated, userController.getResponses)
router.put('/userName', authenticated, upload.single('avatar'), userController.putUser)
router.post('/userName', userController.getUser)
router.post('/upload-file', upload.single('profile_img'), storyController.uploadImg)
// router.post('/signIn', localAuthenticate, userController.signIn)
router.post('/signIn', passport.authenticate('local'), userController.signIn)

router.use('/', apiErrorHandler)
module.exports = router
